spring.application.name=edumatrix

spring.datasource.url=jdbc:mysql://localhost:3306/edumatrix
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=yourSecretKey123
jwt.auth.expiration=86400000
jwt.refresh.expiration=86400000
jwt.account-verification.expiration=86400000
jwt.passwordreset.expiration=86400000
